package transform

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	jsonpatch "github.com/evanphx/json-patch"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

// SplitNewResourceToSkeletonAndPatch takes a complete resource generated by a plugin
// and splits it into a minimal skeleton and a RFC 6902 JSONPatch.
//
// The skeleton contains only: apiVersion, kind, metadata.name, metadata.namespace.
// Everything else (labels, annotations, spec, status, ...) becomes "add" operations
// in the returned patch.
//
// This allows new resources to follow the same skeleton + patches flow as transformed
// resources, keeping the stage directory structure consistent and transparent.
func SplitNewResourceToSkeletonAndPatch(resource unstructured.Unstructured) (unstructured.Unstructured, jsonpatch.Patch, error) {
	full := resource.Object
	if full == nil {
		return unstructured.Unstructured{}, nil, fmt.Errorf("resource has nil Object")
	}

	skeleton := buildSkeleton(full)

	ops := buildPatchOps(full, skeleton)

	if len(ops) == 0 {
		return unstructured.Unstructured{Object: skeleton}, nil, nil
	}

	opsJSON, err := json.Marshal(ops)
	if err != nil {
		return unstructured.Unstructured{}, nil, fmt.Errorf("failed to marshal patch ops: %w", err)
	}

	patch, err := jsonpatch.DecodePatch(opsJSON)
	if err != nil {
		return unstructured.Unstructured{}, nil, fmt.Errorf("failed to decode patch: %w", err)
	}

	return unstructured.Unstructured{Object: skeleton}, patch, nil
}

// buildSkeleton creates a minimal resource map with only the fields kustomize needs
// to target the resource: apiVersion, kind, metadata.name, metadata.namespace.
func buildSkeleton(full map[string]interface{}) map[string]interface{} {
	skel := map[string]interface{}{}

	if v, ok := full["apiVersion"]; ok {
		skel["apiVersion"] = v
	}
	if v, ok := full["kind"]; ok {
		skel["kind"] = v
	}

	fullMeta, _ := full["metadata"].(map[string]interface{})
	if fullMeta != nil {
		skelMeta := map[string]interface{}{}
		if v, ok := fullMeta["name"]; ok {
			skelMeta["name"] = v
		}
		if v, ok := fullMeta["namespace"]; ok {
			skelMeta["namespace"] = v
		}
		skel["metadata"] = skelMeta
	}

	return skel
}

// buildPatchOps generates RFC 6902 "add" operations for everything in full
// that is not present in skeleton.
func buildPatchOps(full, skeleton map[string]interface{}) []patchOp {
	var ops []patchOp

	skelMeta, _ := skeleton["metadata"].(map[string]interface{})
	fullMeta, _ := full["metadata"].(map[string]interface{})

	// metadata subfields not in skeleton (labels, annotations, etc.)
	if fullMeta != nil && skelMeta != nil {
		metaKeys := sortedKeys(fullMeta)
		for _, key := range metaKeys {
			if _, inSkel := skelMeta[key]; !inSkel {
				ops = append(ops, patchOp{
					Op:    "add",
					Path:  "/metadata/" + escapeJSONPointer(key),
					Value: fullMeta[key],
				})
			}
		}
	}

	// top-level fields not in skeleton (spec, status, data, etc.)
	topKeys := sortedKeys(full)
	for _, key := range topKeys {
		if _, inSkel := skeleton[key]; !inSkel {
			ops = append(ops, patchOp{
				Op:    "add",
				Path:  "/" + escapeJSONPointer(key),
				Value: full[key],
			})
		}
	}

	return ops
}

type patchOp struct {
	Op    string      `json:"op"`
	Path  string      `json:"path"`
	Value interface{} `json:"value"`
}

func sortedKeys(m map[string]interface{}) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// escapeJSONPointer escapes ~ and / per RFC 6901.
func escapeJSONPointer(s string) string {
	// ~ must be escaped first (before /)
	s = strings.ReplaceAll(s, "~", "~0")
	s = strings.ReplaceAll(s, "/", "~1")
	return s
}
